os: linux
language: node_js
node_js:
  - 14
dist: jammy
services:
  - xvfb
addons:
  chrome: stable
cache:
  directories:
    - ./.yarn/cache
    - $HOME/.npm
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
    # Upgrade Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  # Then the local Yarn 2 should be available and get used
  - yarn -v
install: yarn --immutable
script:
  # 
  # run build script specified in package.json
  - yarn build --configuration=production
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN  # Set in the settings page of your repository, as a secure variable
  keep_history: true
  on:
    branch: main