language: node_js
node_js:
  - 14
dist: jammy
services:
  - xvfb
addons:
  chrome: stable
cache:
  directories:
    - ./.yarn/cache
    - $HOME/.npm
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
    # Upgrade Yarn
  - curl -o- -L https://yarnpkg.com/install.sh | bash
  - export PATH="$HOME/.yarn/bin:$PATH"
  # Then the local Yarn 2 should be available and get used
  - yarn -v
install: yarn
script:
  # run build script specified in package.json
  - npm i webdriver-manager
  - yarn --immutable
  # call script for deploying of produced artifacts
  - bash ./.travis-deploy.sh

