language: node_js
node_js:
  - 14
sudo: false
dist: trusty
addons:
  chrome: stable
cache:
  directories:
    - $HOME/.npm
before_install:
  - export CHROME_BIN=chromium-browser
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install codecov -g
  # Upgrade Yarn
  - yarn set version berry
  # Then the local Yarn 2 should be available and get used
  - yarn -v
  - yarn --immutable
script:
  # run build script specified in package.json
  - npm i webdriver-manager
  - yarn --immutable
  # call script for deploying of produced artifacts
  - bash ./.travis-deploy.sh
after_success:
  - codecov
