#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

npx stylelint "{apps,libs}/**/*.{css,less,sass,scss,sss}"
npx nx run-many --target=lint --all --parallel --fix
npx nx run-many --target=test --all --parallel